### ISSUE TITLE
How to generate grasps for objects from ShapeNet

### ISSUE THREAD

**Issue by bearpaw** [ikalevatykh/mano_grasp#1]
Thanks for the great code! The demo shows how to generate grasp with the default objects in Graspit (which is in `*.iv` format). How can we generate grasp for objects from ShapeNet as discussed in the [paper](https://hassony2.github.io/obman)? Thank you in advance!

**Comment by lwohlhart** [comment]
Hi, 
If you're still interested in this you can checkout my fork of the project https://github.com/lwohlhart/mano_grasp

It adds an object preparation script that you can use to bring any common object dataset into the required graspit format

Make sure you have meshlab installed and you're good

Maybe I'll get a pull-request through...
hth Lucas
